cluster:
  name: "elk-elastic-cluster"
  routing.allocation.awareness.attributes: aws_availability_zone

node:
  name: ${HOSTNAME}
  master: true
  data: true

cloud:
  aws:
    protocol: https
    region: eu-west-2
  node.auto_attributes: true

discovery:
  ec2:
    availability_zones: eu-west-2a,us-west-2b
    node_cache_time: 120s
    groups: ${CLUSTER_SECURITY_GROUP}
  zen:
    hosts_provider: ec2
    join_timeout: 90s
    ping_timeout: 30s

http.port: 9200
transport.tcp.port: 9300
network.host:
- _eth0:ipv4_
- _local_
network.bind_host: 0
network.publish_host: _ec2:privateIp_

plugin.mandatory:
- discovery-ec2
- repository-s3

xpack.security.audit.enabled: true
xpack.security.audit.outputs: [ index ]

xpack.ssl.key:                     /usr/share/elasticsearch/config/node.key
xpack.ssl.certificate:             /usr/share/elasticsearch/config/node.crt
xpack.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/ca.crt" ]

xpack.security.http.ssl.enabled: true 
xpack.security.transport.ssl.enabled: true 

xpack.security.transport.ssl.verification_mode: none
xpack.ssl.verification_mode: none
